### ISSUE TITLE
奔溃

### ISSUE THREAD

**Issue by LPLuck** [yangchong211/LifeHelper#16]
Caused by: io.realm.exceptions.RealmException: CacheHomeNews is not part of the schema for this Realm
                                                                          at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:181)
                                                                          at io.realm.internal.modules.CompositeMediator.getSimpleClassNameImpl(CompositeMediator.java:99)
                                                                          at io.realm.internal.RealmProxyMediator.getSimpleClassName(RealmProxyMediator.java:72)
                                                                          at io.realm.RealmSchema.getTable(RealmSchema.java:177)
                                                                          at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:200)
                                                                          at io.realm.RealmQuery.<init>(RealmQuery.java:154)
                                                                          at io.realm.RealmQuery.createQuery(RealmQuery.java:93)
                                                                          at io.realm.Realm.where(Realm.java:1431)
                                                                          at com.ns.yc.lifehelper.ui.guide.presenter.GuidePresenter.cacheHomeNews(GuidePresenter.java:214)
                                                                          at com.ns.yc.lifehelper.ui.guide.presenter.GuidePresenter.cacheHomeNewsData(GuidePresenter.java:114)
                                                                          at com.ns.yc.lifehelper.ui.guide.view.activity.GuideActivity.initData(GuideActivity.java:104)
                                                                          at com.ycbjie.library.base.mvp.BaseActivity.onCreate(BaseActivity.java:46)
                                                                          at android.app.Activity.performCreate(Activity.java:6807)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2753)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2861) 
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6321) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

**Comment by yangchong211** [comment]
这个问题之前解决了，已经修改了，你在拉一下代码即可。https://github.com/yangchong211/LifeHelper/issues/14
