### ISSUE TITLE
依赖哪里冲突了？

### ISSUE THREAD

**Issue by badguy0827** [yangchong211/LifeHelper#38]
Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: com.yc.statusbar.BuildConfig
        at com.android.tools.r8.utils.ProgramClassCollection.resolveClassConflictImpl(ProgramClassCollection.java:64)
        at com.android.tools.r8.utils.ProgramClassCollection.lambda$create$0(ProgramClassCollection.java:25)
        at com.android.tools.r8.utils.ProgramClassCollection.create(ProgramClassCollection.java:24)
        at com.android.tools.r8.graph.LazyLoadedDexApplication$Builder.build(LazyLoadedDexApplication.java:124)
        at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:123)
        at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
        at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:40)
        at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:110)
        at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:83)

**Comment by youlongxifeng** [comment]
跑不起来，只能看看代码
